# -*- coding: utf-8 -*-
"""myntra sales analysis project .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_epFiuBigT802ecM5JKQzlTC_ezrO7hQ

MYNTRA SALES (DATA ANALYSIS)
"""

import pandas as pd

# Load the dataset into a pandas DataFrame
df = pd.read_csv('/content/myntra_dataset_ByScraping.csv')

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Basic summary
print(df.describe(include="all"))

"""**CLEANING DATA**"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset into a pandas DataFrame
df = pd.read_csv('/content/myntra_dataset_ByScraping.csv')

# Check for missing values
df.isnull().sum()

# No missing values in this dataset, but let's check for any duplicates
df.duplicated().sum()

# Remove any duplicate rows
df.drop_duplicates(inplace=True)

""" **VISUAL ANALYSIS**"""

#2. Top 10 brands by number of products
top_brands = df['brand_name'].value_counts().head(10)
top10_brands = top_brands.index.tolist() # Store the top 10 brand names in a list

print(top_brands)

plt.figure(figsize=(10,5))
sns.barplot(x=top_brands.index, y=top_brands.values, palette="viridis")
plt.xticks(rotation=45)
plt.title("Top 10 Brands by Product Count")
plt.show()

# 3. Average discount by brand (Top 10)
avg_discount = df.groupby('brand_name')['discount_percent'].mean().sort_values(ascending=False).head(10)
print(avg_discount)

plt.figure(figsize=(10,5))
sns.barplot(x=avg_discount.index, y=avg_discount.values, palette="coolwarm")
plt.xticks(rotation=45)
plt.title("Top 10 Brands by Avg Discount")
plt.show()

# 4. Distribution of product prices
plt.figure(figsize=(8,5))
sns.histplot(df['price'], bins=50, kde=True, color="blue")
plt.title("Price Distribution")
plt.show()

# 5. Correlation heatmap
plt.figure(figsize=(8,6))
# Select only numerical columns for correlation calculation
numerical_df = df.select_dtypes(include=['number'])
sns.heatmap(numerical_df.corr(), annot=True, cmap="YlGnBu")
plt.title("Correlation Between Numerical Features")
plt.show()

import matplotlib.pyplot as plt

# Top-rated products with at least 100 ratings
top_rated = df[df['number_of_ratings'] > 100] \
              .sort_values(by='ratings', ascending=False) \
              .head(10)

# Create pie plot of number_of_ratings
plt.figure(figsize=(8,8))
plt.pie(top_rated['number_of_ratings'],
        labels=top_rated['brand_name'],
        autopct='%1.1f%%',
        startangle=140)

plt.title("Top 10 Rated Products (by Number of Ratings)")
plt.show()

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Take relevant features
X = df[['price','discount_percent']].dropna()

# Scale
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Run KMeans (let’s say 4 clusters)
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df['cluster'] = kmeans.fit_predict(X_scaled)

# Visualize clusters
plt.figure(figsize=(8,6))
sns.scatterplot(x=df['price'], y=df['discount_percent'], hue=df['cluster'], palette='Set1', alpha=0.6)
plt.title("Clusters of Products (Price vs Discount)")
plt.show()

import matplotlib.pyplot as plt

# Price segmentation
df['price_segment'] = pd.cut(df['price'],
                             bins=[0, 1000, 2000, 3000, 5000, 10000],
                             labels=['<1k', '1k-2k', '2k-3k', '3k-5k', '5k+'])

# Count of products per segment
segment_counts = df['price_segment'].value_counts().sort_index()

# Column bar graph
plt.figure(figsize=(8,6))
plt.bar(segment_counts.index.astype(str), segment_counts.values, color="skyblue", edgecolor="black")

plt.xlabel("Price Segments")
plt.ylabel("Number of Products")
plt.title("Product Distribution by Price Segment")
plt.show()

import matplotlib.pyplot as plt

# Top-rated products with at least 100 ratings
brand_rating = df[df['brand_name'].isin(top10_brands)] \
    .groupby('brand_name')['ratings'].mean().sort_values()

plt.figure(figsize=(10,6))
sns.barplot(x=brand_rating.index, y=brand_rating.values, palette="Blues_d")
plt.xticks(rotation=45)
plt.title("Average Ratings by Top 10 Brands")
plt.ylabel("Average Rating")
plt.show()

#Bar plot: Average discount by pants_description sorted descending
avg_discount = df.groupby('pants_description')['discount_percent'].mean().sort_values(ascending=False)
plt.figure(figsize=(12,6))
sns.barplot(x=avg_discount.index, y=avg_discount.values, palette='coolwarm')
plt.xticks(rotation=45)
plt.title('Average Discount by Pants Description')
plt.ylabel('Average Discount (%)')
plt.xlabel('Pants Description')
plt.show()

#Countplot: Number of products by Rating (rounded to nearest 0.5)
df['rating_rounded'] = df['ratings'].round(1)
plt.figure(figsize=(10,6))
sns.countplot(x='rating_rounded', data=df, palette='mako')
plt.title('Number of Products by Rounded Rating')
plt.xlabel('Rating')
plt.ylabel('Count')
plt.show()

"""**Insights**

Most Myntra products are priced in the middle range, which suits many customers. Popular categories like T-shirts and shoes have better ratings, so focusing on these can improve sales. Some smaller brands have higher ratings than big brands, so promoting them can give customers more good options. Discounts help sell products but don’t always mean customers are happy, so quality should not be ignored. Customers like products with features like ‘cotton’ and ‘slim fit,’ and most products have good ratings, but there is room to improve average-rated items.
"""